services:
  web_server:
    build: .
    ports:
      - ${WEB_SERVER_PORT}:3000
    depends_on:
      - database
    container_name: 2dam-booking-webserver
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - ./2dam_booking:/web
    environment:
      - TZ=Europe/Berlin
    restart: always
  database:
    image: yobasystems/alpine-mariadb:11.4.5
    container_name:  2dam-booking-db
    ports:
      - "2222:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Berlin
    volumes:
     - ./data/db/mysql:/var/lib/mysql